---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx 
summary: Scopri come configurare un backend ONTAP con i driver NAS ONTAP. 
---
= Configurare un backend NAS ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Informazioni sulla configurazione di un backend ONTAP con driver NAS ONTAP e Cloud Volumes ONTAP.

* link:ontap-nas-prep.html["Preparazione"]
* link:ontap-nas-examples.html["Configurazione ed esempi"]



WARNING: I clienti devono utilizzare `ontap-nas` driver per carichi di lavoro di produzione che richiedono protezione dei dati, disaster recovery e mobilità. Astra Control offre protezione perfetta, disaster recovery e mobilità per i volumi creati con `ontap-nas` driver. Il `ontap-nas-economy` Il driver deve essere utilizzato solo in casi di utilizzo limitato in cui si prevede un utilizzo dei volumi molto più elevato rispetto a quello supportato da ONTAP, senza requisiti di protezione dei dati, disaster recovery o mobilità (spostamento di volumi tra cluster Kubernetes).



== Autorizzazioni utente

Astra Trident prevede di essere eseguito come amministratore di ONTAP o SVM, in genere utilizzando `admin` utente del cluster o un `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo. Per le implementazioni di Amazon FSX per NetApp ONTAP, Astra Trident prevede di essere eseguito come amministratore di ONTAP o SVM, utilizzando il cluster `fsxadmin` utente o a. `vsadmin` Utente SVM o un utente con un nome diverso che ha lo stesso ruolo. Il `fsxadmin` user è un sostituto limitato per l'utente amministratore del cluster.


NOTE: Se si utilizza `limitAggregateUsage` parametro, sono richieste le autorizzazioni di amministrazione del cluster. Quando si utilizza Amazon FSX per NetApp ONTAP con Astra Trident, il `limitAggregateUsage` il parametro non funziona con `vsadmin` e. `fsxadmin` account utente. L'operazione di configurazione non riesce se si specifica questo parametro.

Sebbene sia possibile creare un ruolo più restrittivo all'interno di ONTAP che un driver Trident può utilizzare, non lo consigliamo. La maggior parte delle nuove release di Trident chiamerà API aggiuntive che dovrebbero essere considerate, rendendo gli aggiornamenti difficili e soggetti a errori.
