---
sidebar: sidebar 
permalink: trident-use/worker-node-prep.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, nfs, iscsi, kubernetes clusters 
summary: Tutti i nodi di lavoro nel cluster Kubernetes devono essere in grado di montare i volumi di cui si è eseguito il provisioning per i pod. Se si utilizzano i driver ontap-nas, ontap-nas-Economy, ontap-nas-flexgroup per uno dei backend, i nodi di lavoro necessitano degli strumenti NFS. In caso contrario, richiedono gli strumenti iSCSI. 
---
= Preparare il nodo di lavoro
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Tutti i nodi di lavoro nel cluster Kubernetes devono essere in grado di montare i volumi di cui si è eseguito il provisioning per i pod. Se si utilizza `ontap-nas`, `ontap-nas-economy`, o. `ontap-nas-flexgroup` Driver per uno dei tuoi back-end, i nodi di lavoro hanno bisogno degli strumenti NFS. In caso contrario, richiedono gli strumenti iSCSI.

Le versioni recenti di RedHat CoreOS hanno sia NFS che iSCSI installati per impostazione predefinita.


WARNING: È necessario riavviare sempre i nodi di lavoro dopo l'installazione degli strumenti NFS o iSCSI, altrimenti il collegamento dei volumi ai container potrebbe non riuscire.



== Rilevamento del servizio del nodo

A partire dal 22.07, Astra Trident tenta di rilevare automaticamente se il nodo è in grado di eseguire servizi iSCSI o NFS. Astra Trident crea eventi per il nodo per identificare i servizi rilevati. È possibile rivedere questi eventi utilizzando il comando:

[listing]
----
kubectl get event -A --field-selector involvedObject.name=<Kubernetes node name>
----
Trident identifica inoltre i servizi abilitati per ciascun nodo sul nodo Trident CR. Per visualizzare i servizi rilevati, utilizzare il comando:

[listing]
----
tridentctl get node -o wide -n <Trident namespace>
----

NOTE: Il rilevamento del servizio nodo identifica i servizi rilevati ma non garantisce che i servizi siano configurati correttamente. Al contrario, l'assenza di un servizio rilevato non garantisce il mancato funzionamento del montaggio del volume.



== Volumi NFS

[cols="3*"]
|===
| Protocollo | Sistema operativo | Comandi 


| NFS  a| 
RHEL/CentOS 7
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`

|===

NOTE: Assicurarsi che il servizio NFS venga avviato durante l'avvio.



== Volumi iSCSI

Quando si utilizzano volumi iSCSI, considerare quanto segue:

* Ogni nodo del cluster Kubernetes deve avere un IQN univoco. *Questo è un prerequisito necessario*.
* Se si utilizza RHCOS versione 4.5 o successiva, o un'altra distribuzione Linux compatibile con RHEL, con `solidfire-san` Driver ed Element OS 12.5 o versioni precedenti, assicurarsi che l'algoritmo di autenticazione CHAP sia impostato su MD5 in `/etc/iscsi/iscsid.conf`. Gli algoritmi CHAP conformi a FIPS sicuri SHA1, SHA-256 e SHA3-256 sono disponibili con Element 12.7.
+
[listing]
----
sudo sed -i 's/^\(node.session.auth.chap_algs\).*/\1 = MD5/' /etc/iscsi/iscsid.conf
----
* Quando si utilizzano nodi di lavoro che eseguono RHEL/RedHat CoreOS con iSCSI PVS, assicurarsi di specificare `discard` MountOption in StorageClass per eseguire la rigenerazione dello spazio inline. Vedere https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["La documentazione di RedHat"^].


[cols="3*"]
|===
| Protocollo | Sistema operativo | Comandi 


| ISCSI  a| 
RHEL/CentOS
 a| 
. Installare i seguenti pacchetti di sistema:
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. Verificare che la versione di iscsi-initiator-utils sia 6.2.0.874-2.el7 o successiva:
+
`rpm -q iscsi-initiator-utils`

. Impostare la scansione su manuale:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Abilitare il multipathing:
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`

+

NOTE: Assicurarsi `etc/multipath.conf` contiene `find_multipaths no` sotto `defaults`.

. Assicurarsi che `iscsid` e. `multipathd` sono in esecuzione:
+
`sudo systemctl enable --now iscsid multipathd`

. Attivare e avviare `iscsi`:
+
`sudo systemctl enable --now iscsi`





| ISCSI  a| 
Ubuntu
 a| 
. Installare i seguenti pacchetti di sistema:
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. Verificare che la versione Open-iscsi sia 2.0.874-5ubuntu2.10 o successiva (per il bionico) o 2.0.874-7.1ubuntu6.1 o successiva (per il focale):
+
`dpkg -l open-iscsi`

. Impostare la scansione su manuale:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Abilitare il multipathing:
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`

+

NOTE: Assicurarsi `etc/multipath.conf` contiene `find_multipaths no` sotto `defaults`.

. Assicurarsi che `open-iscsi` e. `multipath-tools` sono abilitati e in esecuzione:
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`



|===

NOTE: Per Ubuntu 18.04, è necessario rilevare le porte di destinazione con `iscsiadm` prima di iniziare `open-iscsi` Per avviare il daemon iSCSI. In alternativa, è possibile modificare `iscsi` servizio da avviare `iscsid` automaticamente.
