---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'L"operatore Trident consente di personalizzare il modo in cui Astra Trident viene installato utilizzando gli attributi in `TridentOrchestrator` spec.' 
---
= Personalizzare l'implementazione dell'operatore Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'operatore Trident consente di personalizzare l'installazione di Astra Trident utilizzando gli attributi in `TridentOrchestrator` spec.

Se si desidera personalizzare l'installazione oltre ciò che si desidera `TridentOrchestrator` gli argomenti lo consentono, dovresti considerare di utilizzare `tridentctl` Per generare manifesti YAML personalizzati che è possibile modificare in base alle esigenze.


WARNING: `spec.namespace` è specificato in `TridentOrchestrator` Indicare lo spazio dei nomi in cui è installato Astra Trident. Questo parametro *non può essere aggiornato dopo l'installazione di Astra Trident*. Il tentativo di eseguire questa operazione causa il `TridentOrchestrator` stato in cui passare `Failed`. Astra Trident non deve essere migrato tra spazi dei nomi.



== Opzioni di configurazione

Questa tabella è dettagliata `TridentOrchestrator` attributi:

[cols="3"]
|===
| Parametro | Descrizione | Predefinito 


| `namespace` | Spazio dei nomi in cui installare Astra Trident | "predefinito" 


| `debug` | Attiva il debug per Astra Trident | falso 


| `windows` | Impostazione su `true` Attiva l'installazione su nodi di lavoro Windows. | falso 


| `IPv6` | Installare Astra Trident su IPv6 | falso 


| `k8sTimeout` | Timeout per le operazioni Kubernetes | 30 sec 


| `silenceAutosupport` | Non inviare pacchetti AutoSupport automaticamente a NetApp | falso 


| `enableNodePrep` | Gestire automaticamente le dipendenze dei nodi di lavoro (*BETA*) | falso 


| `autosupportImage` | L'immagine del contenitore per la telemetria AutoSupport | "netapp/trident-autosupport:22.10.0" 


| `autosupportProxy` | Indirizzo/porta di un proxy per l'invio di telemetria AutoSupport | "http://proxy.example.com:8888"[] 


| `uninstall` | Flag utilizzato per disinstallare Astra Trident | falso 


| `logFormat` | Formato di registrazione Astra Trident da utilizzare [text,json] | "testo" 


| `tridentImage` | Immagine Astra Trident da installare | "netapp/trident:21.04" 


| `imageRegistry` | Percorso al registro interno, del formato
`<registry FQDN>[:port][/subpath]` | "k8s.gcr.io/sig-storage (k8s 1.19+) o quay.io/k8scsi" 


| `kubeletDir` | Percorso della directory del kubelet sull'host | "/var/lib/kubelet" 


| `wipeout` | Un elenco di risorse da eliminare per eseguire una rimozione completa di Astra Trident |  


| `imagePullSecrets` | Secrets (segreti) per estrarre immagini da un registro interno |  


| `controllerPluginNodeSelector` | Selettori di nodi aggiuntivi per i pod che eseguono il Plugin CSI del controller Trident. Segue lo stesso formato di pod.spec.nodeSelector. | Nessuna impostazione predefinita; opzionale 


| `controllerPluginTolerations` | Ignora le tolleranze per i pod che eseguono il Plugin CSI del controller Trident. Segue lo stesso formato di pod.spec.Tolerations. | Nessuna impostazione predefinita; opzionale 


| `nodePluginNodeSelector` | Selettori di nodi aggiuntivi per i pod che eseguono il Plugin CSI di Trident Node. Segue lo stesso formato di pod.spec.nodeSelector. | Nessuna impostazione predefinita; opzionale 


| `nodePluginTolerations` | Ignora le tolleranze per i pod che eseguono il Plugin CSI di Trident Node. Segue lo stesso formato di pod.spec.Tolerations. | Nessuna impostazione predefinita; opzionale 
|===

NOTE: Per ulteriori informazioni sulla formattazione dei parametri del pod, vedere link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Assegnazione di pod ai nodi"^].



== Configurazioni di esempio

È possibile utilizzare gli attributi menzionati in precedenza per la definizione `TridentOrchestrator` per personalizzare l'installazione.

.Esempio 1: Configurazione personalizzata di base
[%collapsible%open]
====
Questo è un esempio per una configurazione personalizzata di base.

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Esempio 2: Implementazione con selettori di nodo
[%collapsible%open]
====
Questo esempio illustra come può essere implementato Trident con i selettori di nodo:

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.Esempio 3: Implementazione su nodi di lavoro Windows
[%collapsible%open]
====
In questo esempio viene illustrata la distribuzione su un nodo di lavoro Windows.

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====